[package]
name = "os"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
riscv = "0.13.0"
sbi-rt = { version = "0.0.2", features = ["legacy"] }
